### ISSUE TITLE
Can't get module working

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/expanding_formatter#1]
I'm testing this module with Backdrop 1.28.2, but I can't get it to work reliably.

First I've tried to use the module with a view of fields. While its formatters were available, the Expand / Collapse links didn't have any affect. I've then experimented with the formatters and different content view modes on my test site. At a certain point (don't remember exactly), one teaser view mode started to work as expected, and after this also the view of fields worked fine. Encouraged by the success, I installed the module on another site, but couldn't get it to work at all there.

If others had similar issues, what did you do to get the module working?

**Comment by laryn** [comment]
@olafgrabienski I haven't used this module in many years, but I spun up a demo site and installed it and didn't see an issue with basic usage:

https://github.com/user-attachments/assets/61029314-5c68-4d10-a5f9-70be9458480e

Do you have any errors in the console?

**Comment by olafgrabienski** [comment]
@laryn Many thanks for testing the module! I've tried _Expanding Formatter_ once more, this time on two sites. On both sites, the formatter works fine for the Body field in the Default display mode of a the Page content type (as shown in your screencast). But the formatter does _not_ work in a view with the Body and other fields of the same content type.

There are no errors in the console, btw.

**Comment by olafgrabienski** [comment]
I was able to reproduce the different behavior (node okay, view of fields not) on a [demo site](https://latest-w1t7yji22scobuwadgbj9uozlffnp10j.tugboatqa.com).

In the view, the body text doesn't get trimmed, even if there is an ellipsis and an Expand button (which doesn't react when you click it). See also the 2nd screenshot below.

---

NODE default display / OK:

<img src="https://github.com/user-attachments/assets/74801d7b-dcdd-4073-99d1-dc39e3f27a35" width=500>

---

VIEW of fields with the same node, amongst others / not working (note also the interesting display of the 2nd node):

<img src="https://github.com/user-attachments/assets/8c2b2e44-7a8b-445f-aa09-473e9e7b1969" width=500>

**Comment by laryn** [comment]
@olafgrabienski I did some cleanup here and stripped out a bunch of stuff. I think the basic functionality is working now and I've made a new release.

**Comment by olafgrabienski** [comment]
@laryn Thanks for the cleanup and the new release! You're right, the basics are working now. (Found a related problem, will open a separate issue.)
